name: Run Web Scraping Script Every Hour

on:
  schedule:
    # This cron expression schedules the workflow to run every hour
    - cron: "0 * * * *"
  workflow_dispatch: # Allows manual triggering of the workflow as well

jobs:
  scrape_jobs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install necessary dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # Step 4: Download Chrome WebDriver
      - name: Download Chrome WebDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Step 5: Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 6: Run the scraping script
      - name: Run web scraping script
        run: |
          python script.py
          
      # Step 7: Upload the CSV results (optional)
      - name: Upload CSV files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: job_csvs
          path: "*.csv"
